<option value="01">Республика Адыгея</option>
<option value="04">Республика Алтай</option>
<option value="22">Алтайский край</option>
<option value="28">Амурская область</option>
<option value="29">Архангельская область</option>
<option value="30">Астраханская область</option>
<option value="02">Республика Башкортостан</option>
<option value="31">Белгородская область</option>
<option value="32">Брянская область</option>
<option value="03">Республика Бурятия</option>
<option value="33">Владимирская область</option>
<option value="34">Волгоградская область</option>
<option value="35">Вологодская область</option>
<option value="36">Воронежская область</option>
<option value="05">Республика Дагестан</option>
<option value="79">Еврейская автономная область</option>
<option value="75">Забайкальский край</option>
<option value="37">Ивановская область</option>
<option value="06">Республика Ингушетия</option>
<option value="38">Иркутская область</option>
<option value="07">Кабардино-Балкарская республика</option>
<option value="39">Калининградская область</option>
<option value="08">Республика Калмыкия</option>
<option value="40">Калужская область</option>
<option value="41">Камчатский край</option>
<option value="09">Карачаево-Черкесская республика</option>
<option value="10">Республика Карелия</option>
<option value="42">Кемеровская область</option>
<option value="43">Кировская область</option>
<option value="11">Республика Коми</option>
<option value="44">Костромская область</option>
<option value="23">Краснодарский край</option>
<option value="24">Красноярский край</option>
<option value="91">Республика Крым</option>
<option value="45">Курганская область</option>
<option value="46">Курская область</option>
<option value="47">Ленинградская область</option>
<option value="48">Липецкая область</option>
<option value="49">Магаданская область</option>
<option value="12">Республика Марий Эл</option>
<option value="13">Республика Мордовия</option>
<option value="77">Москва</option>
<option value="51">Мурманская область</option>
<option value="83">Ненецкий автономный округ</option>
<option value="52">Нижегородская область</option>
<option value="53">Новгородская область</option>
<option value="54">Новосибирская область</option>
<option value="55">Омская область</option>
<option value="56">Оренбургская область</option>
<option value="57">Орловская область</option>
<option value="58">Пензенская область</option>
<option value="59">Пермский край</option>
<option value="25">Приморский край</option>
<option value="60">Псковская область</option>
<option value="61">Ростовская область</option>
<option value="62">Рязанская область</option>
<option value="63">Самарская область</option>
<option value="64">Саратовская область</option>
<option value="14">Республика Саха (Якутия)</option>
<option value="65">Сахалинская область</option>
<option value="66">Свердловская область</option>
<option value="92">Севастополь</option>
<option value="15">Республика Северная Осетия &mdash; Алания</option>
<option value="67">Смоленская область</option>
<option value="26">Ставропольский край</option>
<option value="68">Тамбовская область</option>
<option value="16">Республика Татарстан</option>
<option value="69">Тверская область</option>
<option value="70">Томская область</option>
<option value="71">Тульская область</option>
<option value="17">Республика Тыва</option>
<option value="72">Тюменская область</option>
<option value="18">Удмуртская республика</option>
<option value="73">Ульяновская область</option>
<option value="27">Хабаровский край</option>
<option value="19">Республика Хакасия</option>
<option value="86">Ханты-Мансийский автономный округ - Югра</option>
<option value="74">Челябинская область</option>
<option value="20">Чеченская республика</option>
<option value="21">Чувашская республика</option>
<option value="87">Чукотский автономный округ</option>
<option value="89">Ямало-Ненецкий автономный округ</option>
<option value="76">Ярославская область</option>

<option value="KZ">Казахстан</option>
<option value="BY">Беларусь</option>
<option value="UA">Украина</option>
<option value="CZ">Чехия</option>